name: Trigger Base Branch Change
on:
  pull_request:
    types:
        - edited


jobs:
  trigger_integration:
        name: Test Name
        if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest

        steps:
        - name: trigger integration
          uses: actions/github-script@v6
          with:
            script: |
                    const prNumber = '${{ github.event.pull_request.number }}';
                    const label = 'trigger-second-workflow';
                    const workflowFile = 'second-workflow.yml';
                    const ref = 'main';
                    const label2 = 'force:integration'

                    console.log(`Triggering workflow ${label} for PR ${prNumber}`);

                    // Add label to PR
                    await github.rest.issues.addLabels({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: prNumber,
                    labels: [label2]
                    });
              
              