name: Trigger Base Branch Change
on:
  pull_request:
    types:
        - edited


jobs:
  trigger_integration:
        name: Test Name
        if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest

        steps:
        - name: trigger integration
          uses: actions/github-script@v6
          with:
            script: |
                const prNumber = context.issue.number;
                console.log(prNumber);

                await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'integration.yml',
                ref: 'final-branch'
                });

                console.log(`Second workflow triggered successfully.`);
              
              
