name: Trigger Base Branch Change
on:
  pull_request:
    types:
        - edited


jobs:
  trigger_integration:
        name: Check preconditions and cancel previous jobs
        if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest

        steps:
            - name: trigger integration
              run: |
                echo Muneeb
                BRANCH_REF="${{ github.head_ref }}"
                curl -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/${{ github.repository }}/actions/workflows/integration.yml/dispatches \
                -d "{\"ref\": \"${BRANCH_REF}\"}"