name: Trigger Base Branch Change
on:
  pull_request:
    types:
        - edited


jobs:
  trigger_integration:
        name: Test Name
        if: ${{ github.event.changes.base && github.event.pull_request.base.ref == 'main' }}
        runs-on: ubuntu-latest

        steps:
          - name: Trigger Specific Commit Workflow
            uses: actions/github-script@v6
            with:
              script: |
                await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'integration.yml',
                ref: context.payload.pull_request.head.ref,
                inputs: {
                  sha: context.payload.pull_request.head.sha
                }
                });
        
          
              
              
