name: Manage integration check

on:
  workflow_run:
    workflows: ["Integration tests"]

jobs:
  create-check:
    runs-on: ubuntu-latest
    outputs:
      check_id: ${{ steps.create-check.outputs.result }}
    steps:
      - name: Create check
        uses: actions/github-script@v6
        id: create-check
        if: ${{ github.context.payload.action == 'requested' || github.context.payload.action == 'in_progress' }}
        with:
          script: |
            const head_sha = context.payload.workflow_run.head_sha;
            const check = await github.rest.checks.create({
              ...context.repo,
              head_sha,
              name: "integration-test-result",
              status: "in_progress",
              output: {
                title: "Integration Test Aggregate Result",
                summary: `Synthetic check capturing the result of the <a href="${context.workflow_run.html_url}">integration-test workflow run</a>`,
              }
            });
            return check.data.id;
  update-check:
    needs: [create-check]
    runs-on: ubuntu-latest
    steps:
      - name: Update check result
        uses: actions/github-script@v6
        if: ${{ github.context.payload.action == 'completed' }}
        with:
          script: |
            // Update the check run
            const checkId = ${{ needs.create-check.outputs.check_id }};
            await github.checks.update({
              ...context.repo
              check_run_id: checkId,
              status: "completed",
              conclusion: github.event.workflow_run.conclusion,
            });
